FROM tensorflow/tensorflow:2.18.0-gpu
RUN apt-get update && apt-get -y install ffmpeg wget git nodejs
WORKDIR /inaseg
COPY ./requirements.txt /inaseg/requirements.txt
RUN pip3 install -r /inaseg/requirements.txt
COPY . /inaseg
